name: Publish FFmpeg Binary

on:
  push:
    paths:
      - 'ffmpeg-*.tar.xz'
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run release script
        run: ./scripts/release.sh
        working-directory: ${{ github.workspace }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}